services:
  app:
    image: hello-front
    build:
      context: ./todo-frontend/
      dockerfile: ./todo-frontend/Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8080/api/
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports: 
      - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/
    container_name: hello-front
  debug-helper:
    image: busybox
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: redis:latest
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    ports: 
      - 6379:6379
    environment:
      - REDIS_PASSWORD=example
      - REDIS_PORT=6379
  server:
    image: todo-backend
    build:
      context: ./todo-backend/
      dockerfile: ./todo-backend/Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    environment: 
      - REDIS_URL=http://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo_back
    depends_on:
      - mongo
      - redis
  nginx:
    image: nginx:1.27.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
